### ISSUE TITLE
Atlas Skeleton not running

### ISSUE THREAD

**Issue by luyandasiko** [atlasphp/Atlas.Cli#12]
Okay I have come across this library last night and I have been trying to build my ORM classes from a database using the command below:

`lib/bin/atlas-skeleton.php \ --conn=dev/demo/config/conn.php \ --dir=src/App/Domain/Model \ --table=stories Demo\\App\\Domain\\Model\\Story`

However, when running this command in Powershell I get the following message:

> Please provide a namespace; e.g. App\\DataSource\\Type.

When I use GitBash I with the same command I get a total different output:

`Generating skeleton data source classes.
Namespace: --conn=dev/demo/config/conn.php
Directory: C:\wamp64\var\www\atlas-core
 Skipped: mkdir C:\wamp64\var\www\atlas-core\--conn=dev/demo/config/conn.php\

Fatal error: Uncaught exception 'Atlas\Cli\Exception' with message 'file_put_con                                                   tents(C:\wamp64\var\www\atlas-core\--conn=dev/demo/config/conn.php\--conn=dev/de                                                   mo/config/conn.phpMapper.php): failed to open stream: No such file or directory'                                                    in C:\wamp64\var\www\atlas-core\lib\atlas\cli\src\Fsio.php:71
Stack trace:
#0 C:\wamp64\var\www\atlas-core\lib\atlas\cli\src\Skeleton\Skeleton.php(421): At                                                   las\Cli\Fsio->put('C:\\wamp64\\var\\w...', '<?php\nnamespace...')
#1 C:\wamp64\var\www\atlas-core\lib\atlas\cli\src\Skeleton\Skeleton.php(372): At                                                   las\Cli\Skeleton\Skeleton->createClass('Mapper', '<?php\nnamespace...')
#2 C:\wamp64\var\www\atlas-core\lib\atlas\cli\src\Skeleton\Skeleton.php(141): At                                                   las\Cli\Skeleton\Skeleton->createClasses()
#3 C:\wamp64\var\www\atlas-core\lib\atlas\cli\src\Skeleton\SkeletonCommand.php(2                                                   31): Atlas\Cli\Skeleton\Skeleton->__invoke(Object(Atlas\Cli\Skeleton\SkeletonInp                                                   ut))
#4 C:\wamp64\var\www\atlas-core\lib\atlas\cli\src\Skeleton\SkeletonCommand.php(1                                                   41): Atlas\Cli\Skeleton\SkeletonCommand->runSkeleton()
 in C:\wamp64\var\www\atlas-core\lib\atlas\cli\src\Fsio.php on line 71
`

Seems like the issue is with the ordering of the command parameters I could be wrong but connection parameter seems to be swiped for the namespace.

What is the correct way of running these command?

**Comment by pmjones** [comment]
/me ponders

It looks like you're trying this on Windows, in which case you might not need the `\` to spread the command across multiple lines. Try doing it on one line without the `\` characters and tell me how that works for you.

**Comment by luyandasiko** [comment]
@pmjones Thanks your suggestion worked like a charm.
