### ISSUE TITLE
Failure: table not found

### ISSUE THREAD

**Issue by James-A1** [atlasphp/Atlas.Cli#16]
Hi, just got started with the cli.

 Running
```./vendor/bin/atlas-skeleton.php --conn=conn.php dir=src/App/DataSource --table=farms App\\DataSources\\Farms```

Gives me an error:
`--Failure: table 'farms' not found`
I checked my database, the tables are there.

I am using pgsql. Here is my `conn.php`:
```
<?php

return [
	'pgsql:dbname=mydb;host=localhost;port=5432',
	'root',
	''
];
```

**Comment by froschdesign** [comment]
@James-A1 
I do not know your configuration. So try adding the [schema](https://www.postgresql.org/docs/current/static/ddl-schemas.html) before the table name.

**Comment by James-A1** [comment]
Thanks, it worked by prefixing the table name with `public.` . Closing this issue.
