### ISSUE TITLE
Provide setters for database config

### ISSUE THREAD

**Issue by shameerc** [atlasphp/Atlas.Cli#2]
I am currently trying to create a wrapper for Atlas.Cli in [my project](https://github.com/shameerc/slim-skeleton) (which uses Aura.di), so that I don't need to go to vendors folder to generate classes. I am looking for a way to pass the db configuration, which is already defined in  config file. Is there a way I can programmatically provide the config rather than using cli options? Or what would be the right way to do it.

Thanks

**Comment by pmjones** [comment]
Interesting. What format is the config file in?

**Comment by shameerc** [comment]
I'm just playing around with the Orm, so thought this would be a nice addition.
Right now the database config is like 

```
'database' => [
    'dbname' => getenv('DB_DATABASE'),
    'user' => getenv('DB_USERNAME'),
    'password' => getenv('DB_PASSWORD'),
    'host' => getenv('DB_HOST'),
    'driver' => getenv('DB_DRIVER'),
],
```

I like to pass the array instead of dsn, but it should be fine as long as I can set the connection.

**Comment by pmjones** [comment]
/me ponders

One way that would work with `atlas-skeleton` as it is now, would be to have the connection-array file include the config file, then build the appropriate array for the CLI tool. Here's an example:

``` php
// conn.php
$config = require 'app/config/config.php';
extract $config['database'];
return [
    "$driver:$host,dbname=$dbname",
    $user,
    $password
];
```

You can then call `atlas-skeleton --conn=conn.php`.

It does mean creating an extra conn.php file (or whatever you want to call it) specifically for Atlas.Cli, but it has the benefit of using your standard configuration setup.

Does that help, or is a programmatic method still preferable?

**Comment by shameerc** [comment]
This will help, but I prefer not to create an extra file for connection. In fact, in future we might need this cli to be a part of a framework than just a vendor package.
I have other questions too which are more general, but is this the right place to ask? 

Thanks :)

**Comment by pmjones** [comment]
This is a good place to ask.

All right: in a perfect world, how would you like the DB values to be set? (That answer will help me figure out what to do.)

**Comment by pmjones** [comment]
@shameerc Any further thoughts on how you'd like to see it implemented?

**Comment by shameerc** [comment]
Hey, I'm sorry for late response. Forgot to check this again.
Ideally I will create an array of db configuration, something like I mentioned [here](https://github.com/atlasphp/Atlas.Cli/issues/2#issuecomment-188387712). This is for Doctrine, but Laravel also specifies the config as an array. If the library requires dsn, I will still have this array and will create the dsn using the values and pass it to the DSN, which is what I'm doing right now for Atlas.

My other questions is, since Atlas is for persistence model, would you recommend the application to have an additional layer for domain model? Or what would be the best way to structure the project?

Update: Spot2 Datamapper has an [addConnection](https://github.com/vlucas/spot2#connecting-to-a-database) method, which accepts both dsn and dbal compatible array of config, which seems nice.

**Comment by pmjones** [comment]
Hi @shameerc,

> Hey, I'm sorry for late response. Forgot to check this again.

No problem; @harikt will confirm that I am terribly slow to respond myself.

> Ideally I will create an array of db configuration, something like I mentioned here. This is for Doctrine, but Laravel also specifies the config as an array. If the library requires dsn, I will still have this array and will create the dsn using the values and pass it to the DSN, which is what I'm doing right now for Atlas.

(/me nods)

If we want to use existing config array keys, the problem is that Atlas will then have to figure out which array keys go in which places when putting together the DSN (and which ones represent the username and password). That's likely to change from project to project, so we'd need some "standard" config key names for Atlas. Does that make sense?

> My other questions is, since Atlas is for persistence model, would you recommend the application to have an additional layer for domain model? Or what would be the best way to structure the project?

It depends on the complexity of the project. What I expect with Atlas is that the persistence model is probably enough to get stated with, for very early in the project. Then, as you begin to need domain behaviors, you can add trivial methods to a custom Record object while fleshing out the domain. Finally, as the domain model becomes more complex, you can create a repository that accesses Atlas to create-and-return domain model objects (which are themselves populated by the persistence model objects). That last one is where things become "expensive" but it's also where you get good separation of domain from persistence. Does that begin to help?

**Comment by pmjones** [comment]
@shameerc I have created a "shameerc" branch for you to look at. In it, the SkeletonFactory and the Skeleton class now take an optional 3rd constructor argument, $conn, that should be a sequential array of [dsn, username, password], just as expected with the --conn file return. When you create the skeleton objects in the DI system, you can put together the right config values within the DI system to create the skeleton objects with the $conn value. (The --conn value at the command line will override that default constructor value.) Let me know if that helps, or if I'm moving in the wrong direction.

**Comment by harikt** [comment]
> @harikt will confirm that I am terribly slow to respond myself.

@pmjones this time I smile :) . Though in past sometimes I have got very much frustrated and argued with you. I am trying not to be too [passionate](https://twitter.com/harikt/status/704544805653643264) ;-) .

**Comment by shameerc** [comment]
> If we want to use existing config array keys, the problem is that Atlas will then have to figure out which array keys go in which places when putting together the DSN (and which ones represent the username and password). That's likely to change from project to project, so we'd need some "standard" config key names for Atlas. Does that make sense?

Completely agree. It makes more sense to use dsn array when you want to support any projects. 

> What I expect with Atlas is that the persistence model is probably enough to get stated with, for very early in the project. 

This is what I'm doing now, just wanted to confirm I'm doing it right :) 

Thanks for creating a branch for me ( and making me soon to be famous :D ). I will play around and let you know my thoughts.

**Comment by pmjones** [comment]
> making me soon to be famous

Soon to be? You're famous already! :-)

**Comment by pmjones** [comment]
I think this issue has been addressed with the merge of `shameerc` branch. Let me know if we need to re-open it!
