### ISSUE TITLE
Support for Postgres schemas other than 'public'?

### ISSUE THREAD

**Issue by kevinsmith** [atlasphp/Atlas.Cli#20]
Just tried running the generator bundled with Cassini v3, and it only picked up the Postgres tables in the public schema. What do I need to do to get the generator to support other schemas?

**Comment by froschdesign** [comment]
@kevinsmith 
You must create the connection and set the schema before adding it to the configuration for the skeleton generator.

### Example

```php
$pdo = new PDO(
    'pgsql:dbname=testdb;host=localhost',
    'username',
    'password',
);
$pdo->exec('SET search_path TO myschema');

return [
    'pdo'       => [$pdo],
    'namespace' => 'App\\DataSource',
    'directory' => './src/App/DataSource',
];
```

Reference:

```php
public static function new(...$args) : Connection
{
    if ($args[0] instanceof PDO) {
        return new static($args[0]);
    }

    return new static(new PDO(...$args));
}
```

https://github.com/atlasphp/Atlas.Pdo/blob/b64a164290b93bffd2e034dc6e49535afc7dea80/src/Connection.php#L43-L45

**Comment by pmjones** [comment]
@kevinsmith Does the answer from @froschdesign help any? If so, does this sound like a documentation fix, or is something more code-oriented preferred?

**Comment by kevinsmith** [comment]
I'm no longer working on the project in question, so I'm not able to test the solution. It does seem plausible to me though, and if it works, I think that'd just be a documentation fix.

**Comment by froschdesign** [comment]
> I think that'd just be a documentation fix.

👍
