### ISSUE TITLE
Add option to select a single table to generate classes

### ISSUE THREAD

**Issue by jelofson** [atlasphp/Atlas.Cli#22]
Me again. Occasionally, I run the skeleton generator because I updated a table schema. The CLI runs through all tables and generally skips any updates for those that have not changed. The only issue I have is that I sometimes have "extra" tables that I don't need or want classes for, so then I go and delete the generated classes. It might be sort of handy to have an arg to specify which table you want to run the skeleton on. Just a though.

**Comment by pmjones** [comment]
That's a neat idea. If you want to send along a PR for it, I'd be happy to review!

**Comment by jelofson** [comment]
What the hell? You want me to actually do some work? You know I hate how much that interferes with my sitting around time! Ok, I will have a gander and see what I can come up with.

**Comment by jelofson** [comment]
Progress...sort of. My compromise solution involves adding a 'tables' config element to the array, which would effectively whitelist which tables you want to create classes for. It's easy to tweak if you just want to specify as single table. 

https://github.com/jelofson/Atlas.Cli/tree/tables

Need to run some additional checks with invalid table names, but can see the progress there. Comments welcome.

**Comment by pmjones** [comment]
I think that's a productive avenue. (I thought I had something like that in there already, but I must be mis-remembering.)

**Comment by pmjones** [comment]
(thinking further)

 I wonder, since your specific issue is that you need to *delete* some generated classes, if it might be better to have an "exclude" variation on the name.

**Comment by pmjones** [comment]
OMG THERE IS A WAY TO SKIP TABLES ALREADY

And it is completely unintuitive! :-(

Cf. http://atlasphp.io/cassini/skeleton/usage.html#1-2-1-3 , the 'transform' value: set a table name to `null` to skip the table completely.

Will that do the trick for you?

**Comment by jelofson** [comment]
That might just do it. Let me take a look...thanks!

**Comment by sunkan** [comment]
@pmjones 

I use this code to filter the tables. Maybe we should update the documentation with it as an example to illustrate an easy way to filter tables. 

```php
'transform' => static function (string $table): ?string {
	return [
		'accounts' => 'Account',
		'accountTokens' => 'AccountToken',
	][$table] ?? null;
},
```

**Comment by pmjones** [comment]
@sunkan "Maybe we should update the documentation with it as an example" -- agreed, or with something like it. Having that feature buried down in Transformation means it is just not obvious enough.

**Comment by jelofson** [comment]
I can confirm that this worked fine for me, so I think we can close this. Just need some added documentation.
