### ISSUE TITLE
Failure: <table name> not found

### ISSUE THREAD

**Issue by fredbliss** [atlasphp/Atlas.Cli#6]
Hello gents,

As I try to run atlas-skeleton, I notice that I've received the error as stated above.  (Replace `<table name>` with the name of the table that I'm specifying in the CLI with the --table parameter.)

`Failure: <table name> not found`

Am I wrong to assume that the table/schema should be created for me?  Just wondering if I'm misunderstanding what the package does.  Does it rather inspect and build the files based on my own schema?  That must be it...

Thanks!

**Comment by pmjones** [comment]
> Am I wrong to assume that the table/schema should be created for me?

Yes, this is incorrect ...

> Does it rather inspect and build the files based on my own schema?

... and yes, this is correct.

The intent here is that the table has already been created, and that Atlas reads it to generate a table class. As you modify the schema yourself, you can re-run the skeleton tool to regenerate the table class.

Does that help to clarify?

**Comment by fredbliss** [comment]
Very much so, thanks!
