### ISSUE TITLE
Ideas / suggestions needed for extending the template files

### ISSUE THREAD

**Issue by harikt** [atlasphp/Atlas.Cli#7]
Hi @pmjones ,

Lately I have been playing with atlas orm. I / we wished there is some way of flexibility we could bring into the template files. https://github.com/atlasphp/Atlas.Cli/blob/28b09d346b2b113c8f55e0b75edf4b399ff0fa04/templates/Record.tpl#L9 . Example , we plan to extend some classes for generic type of functionality. Say `created_at` , `updated_at` etc. Yes, if there is some way like we provide namespace via arguments we could make the change.

Don't feel wrong, that I am asking you to do the same. I understand this can be done as we do like namespace / table name etc via arguments. The problem is when you want to extend different classes the arguments list increases.

Do you think it may be a good idea to use a config file as we do for the connection so things like prefix, namespace etc can be defined there ?

Thank you

**Comment by pmjones** [comment]
(/me nods) Yeah, that might be a good idea. I think it would require changing the config file format to something like this:

``` php
<?php return [
    'conn' => [ /* pdo connection params */ ],
    'tpl' => /* path to templates */,
];
```

Thoughts?

**Comment by pmjones** [comment]
Hm, and adding a `$tpl` param to the Skeleton constructor.

**Comment by harikt** [comment]
ie a good call. I will think and try to send a PR accordingly.

Thank you for your consideration.

**Comment by pmjones** [comment]
Right on. For what it's worth, I don't think we'll need params for every possible template variable; I think it will be enough to pass the connection and the template path, and let people do what they want inside the templates.

**Comment by pmjones** [comment]
@harikt Any further thoughts on this, or PRs that you'd like to send along?

**Comment by harikt** [comment]
Sorry that I didn't find the time to send the PR. I don't know if I could find the same for the current time. Got a bit busy with some other stuffs.

If the issue is still open when I get some time I will send, else you could also close this for it is not an urgent one.

Thank you.

**Comment by pmjones** [comment]
Thanks @harikt  -- closing for "lack of urgency." Can re-open as needed (or send a PR as you have time).
